version: 2
jobs:
  build:
    docker:
      - image: rust:stretch

    steps:
      - checkout

      - run:
          name: Test
          command: cargo test

      - run:
          name: Generate docs
          command: cargo doc
