version: 2
jobs:
  build:
    docker:
      - image: rust:stretch

    steps:
      - checkout

      - run:
        name: Update rust nightly
        command: rustup update nightly

      - run:
        name: Switch to rust nightly
        command: rustup default nightly

      - run:
          name: Test
          command: cargo test

      - run:
          name: Generate docs
          command: cargo doc
